/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookdemo;

/**
 *
 * @author madison.hubbard
 */
public class BookForm extends javax.swing.JFrame {

    /**
     * Creates new form BookForm
     */
    public BookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtISBN = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnBookDefault = new javax.swing.JButton();
        lblBook = new javax.swing.JLabel();
        btnBookCustom = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboPizzaType = new javax.swing.JComboBox();
        cboSize = new javax.swing.JComboBox();
        txtQty = new javax.swing.JTextField();
        btnPizzaDefault = new javax.swing.JButton();
        lstOrder = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        btnPizzaCustom = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtISBN.setBorder(javax.swing.BorderFactory.createTitledBorder("ISBN"));

        txtTitle.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));

        txtAuthor.setBorder(javax.swing.BorderFactory.createTitledBorder("Author"));

        txtPrice.setBorder(javax.swing.BorderFactory.createTitledBorder("Price"));

        btnBookDefault.setText("Add Book Default");
        btnBookDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookDefaultActionPerformed(evt);
            }
        });

        lblBook.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Information"));

        btnBookCustom.setText("Add Book Custom");
        btnBookCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookCustomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblBook, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btnBookDefault))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookCustom)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookDefault))
                .addGap(11, 11, 11)
                .addComponent(btnBookCustom)
                .addGap(18, 18, 18)
                .addComponent(lblBook, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book Demo", jPanel1);

        jLabel1.setText("Welcome to Cuyamaca Pizzaria ");

        cboPizzaType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pepperoni", "Sausage", "Meat Lovers", "Cheese", "Veggie" }));
        cboPizzaType.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Type"));
        cboPizzaType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPizzaTypeActionPerformed(evt);
            }
        });

        cboSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large" }));
        cboSize.setBorder(javax.swing.BorderFactory.createTitledBorder("Size"));

        txtQty.setBorder(javax.swing.BorderFactory.createTitledBorder("Qty"));

        btnPizzaDefault.setText("Order Pizza Default");
        btnPizzaDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaDefaultActionPerformed(evt);
            }
        });

        jLabel2.setText("Order Information");

        btnPizzaCustom.setText("Order Pizza Custom");
        btnPizzaCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaCustomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lstOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(cboPizzaType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPizzaDefault))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPizzaCustom)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPizzaDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPizzaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(btnPizzaCustom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pizza Demo", jPanel2);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(666); 
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBookDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookDefaultActionPerformed
        // TODO: test out our Book object 
        // local variables for ISBN, title, etc. 
        String isbn = txtISBN.getText(); 
        String title = txtTitle.getText(); 
        String author = txtAuthor.getText(); 
        
        // for float, int, double, we need to convert string to the appropriate data type 
        // float someVar = float.parseFloat( stringArg     Argument...)
        // int someVar = Integer.parseInt( stringArg ) // usually the getText method btw
        // double someVar = Double.parseDouble (stringArg) 
        float price = Float.parseFloat(txtPrice.getText()); 
        
        // instantiate our Book into an object, set properties & get book info 
        // use the default constructor approach and then set all of the properties 
        Book myBook = new Book(); // calls the default constructor (no arguments) 
        
        // now that we have instantiated the book, we can set the various properties 
        myBook.setAuthor(author); 
        myBook.setIsbn(isbn);
        myBook.setPrice(price); 
        myBook.setTitle(title); 
        lblBook.setText(myBook.getBookInfo()); 
        
        
        
        
        
    }//GEN-LAST:event_btnBookDefaultActionPerformed

    private void btnBookCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookCustomActionPerformed
         
        String isbn = txtISBN.getText(); 
        String title = txtTitle.getText(); 
        String author = txtAuthor.getText(); 
        float price = Float.parseFloat(txtPrice.getText()); 
        
        
        // instantiate our book using the custom constructor
        Book myBook = new Book(title, author, isbn, price);  
        // note by using the custom sonstructor, we dont have the inline code to set the various properties, see above
        
        // display the book info 
        lblBook.setText(myBook.getBookInfo());  
        
        
        
    }//GEN-LAST:event_btnBookCustomActionPerformed

    private void btnPizzaDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaDefaultActionPerformed
      // to do: make an array of prices 
        float prices[] = {5.00f, 7.50f, 10.00f}; 
        
        // to convert a string to an integer use parseInt 
        int qty = Integer.parseInt(txtQty.getText()); 
        
        
        // read a combo box, getSelectedItem().toString() this returns displayed text 
   String pizzaType = cboPizzaType.getSelectedItem().toString(); 
   
   String size = cboSize.getSelectedItem().toString();  
   int idx = cboSize.getSelectedIndex();  // gets index of selecetd item
   
   // get the price out of our prices array 
   // if no item is selected a combo box returns -1
   if(idx >= 0) {
       // if this is true, then we have a valid size 
   float price = prices[idx]; 
        // create our pizza object with the default constructor 
   Pizza myPizza = new Pizza(); 
   
   // once we instantiate our pizza, we set the various properties 
   myPizza.setPizzaType(pizzaType); 
   myPizza.setPrice(price);
   myPizza.setQty(qty); 
   myPizza.setSize(size); 
   
   // last- we display the order info...
   String info = myPizza.getPizzaInfo(); 
   
   lstOrder.add(info); 
        
   } // end if idx >= 0
   else { 
       // to do: some sort of error message 
       
   }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnPizzaDefaultActionPerformed

    private void cboPizzaTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPizzaTypeActionPerformed
        
        
        
    }//GEN-LAST:event_cboPizzaTypeActionPerformed

    private void btnPizzaCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaCustomActionPerformed
        
        // to do: make an array of prices 
        float prices[] = {5.00f, 7.50f, 10.00f}; 
        
        // to convert a string to an integer use parseInt 
        int qty = Integer.parseInt(txtQty.getText()); 
        
        
        // read a combo box, getSelectedItem().toString() this returns displayed text 
   String pizzaType = cboPizzaType.getSelectedItem().toString(); 
   
   String size = cboSize.getSelectedItem().toString();  
   int idx = cboSize.getSelectedIndex();  // gets index of selecetd item
   
   // get the price out of our prices array 
   // if no item is selected a combo box returns -1
   if(idx >= 0) {
       // if this is true, then we have a valid size 
   float price = prices[idx]; 
        // create our pizza object with the custom constructor 
   // note the properties are all set in the argument 
   Pizza myPizza = new Pizza(pizzaType, size, qty, price); 
   
  
   
   // last- we display the order info...
   String info = myPizza.getPizzaInfo(); 
   
   lstOrder.add(info); 
        
   } // end if idx >= 0
   else { 
       // to do: some sort of error message 
       
   }

   
    }//GEN-LAST:event_btnPizzaCustomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookCustom;
    private javax.swing.JButton btnBookDefault;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPizzaCustom;
    private javax.swing.JButton btnPizzaDefault;
    private javax.swing.JComboBox cboPizzaType;
    private javax.swing.JComboBox cboSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBook;
    private java.awt.List lstOrder;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
