 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package methods;

/**
 *
 * @author madison.hubbard
 */
public class MethodForm extends javax.swing.JFrame {

    /**
     * Creates new form MethodForm
     */
    public MethodForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput1 = new javax.swing.JTextField();
        txtInput2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        btnFormat = new javax.swing.JButton();
        btnIsInt = new javax.swing.JButton();
        btnParseInt = new javax.swing.JButton();
        btnSearchInt = new javax.swing.JButton();
        btnSearchString = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInput1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input 1"));

        txtInput2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input 2"));

        jLabel1.setText("CS-119 Lab 4");

        jLabel2.setText("Madison Hubbard");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        btnFormat.setText("Format");
        btnFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatActionPerformed(evt);
            }
        });

        btnIsInt.setText("Is Integer");
        btnIsInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsIntActionPerformed(evt);
            }
        });

        btnParseInt.setText("Parse Int");
        btnParseInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParseIntActionPerformed(evt);
            }
        });

        btnSearchInt.setText("Search Int");
        btnSearchInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIntActionPerformed(evt);
            }
        });

        btnSearchString.setText("Search Str");
        btnSearchString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSearchInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnParseInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnFormat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIsInt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInput2))
                        .addGap(18, 18, 18)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormat)
                        .addGap(18, 18, 18)
                        .addComponent(btnIsInt)
                        .addGap(18, 18, 18)
                        .addComponent(btnParseInt)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchInt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchString)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatActionPerformed
        // to do: test out our formatNum user defined method 
       
        
        // input: read the text boxes 
        float number = Float.parseFloat( txtInput1.getText() ); 
        String format = txtInput2.getText(); 
        
        // process: call or invoke our user defined method
        // being a static method (or class method), we use ClassName.methodName()
        // number of arguments must match the number of parameters in the method definition and 
        // and the data types must match
        String result = MyUtils.formatNum(number, format); 
        
        
        
        // output: display the result 
        lblResult.setText(result); 
        
    }//GEN-LAST:event_btnFormatActionPerformed

    private void btnIsIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsIntActionPerformed
        // TO do: test our isInteger() method
        String value = txtInput1.getText();  
        
        // review dual alternative selection structure
        if (MyUtils.isInteger(value)) {
            lblResult.setText("YES"); 
        }
        else {
            lblResult.setText("NO"); 
        }
        
    }//GEN-LAST:event_btnIsIntActionPerformed

    private void btnParseIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParseIntActionPerformed
      // input - read the text box
        String value = txtInput1.getText(); 
        
        // process - call our method to convert the value to an integer
        int result = MyUtils.tryParseInt(value, 0); 
        
        // output - display the result
        lblResult.setText(Integer.toString(result)); 
         
    }//GEN-LAST:event_btnParseIntActionPerformed

    private void btnSearchIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIntActionPerformed
        // TODO: test the findItem() method 
        final int items[] = {1,2,3,4,5,6,7,8,9,10}; 
       String msg = "";  
        // read the text box for the search value 
        // get some mileage out of our user defined method 
        int item = MyUtils.tryParseInt(txtInput1.getText(), 0); 
        
        // call or invole our user define method to search the array 
        int result = MyUtils.findItem(items, item); 
        
        // evaluate our result and display the index if found or a not found 
        // message if not found 
        // hint for excersize 2 of this lab 
        if (result > -1) {
            // found it - display the index or subscript 
            msg = "Found item at subscript " + Integer.toString(result); 
        } 
        else {
            msg = "NOT FOUND"; 
        } 
        // DISPLAY THE RESULT 
        lblResult.setText(msg); 
        
    }//GEN-LAST:event_btnSearchIntActionPerformed

    // lab 4 excersize 1, step 19
    private void btnSearchStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStringActionPerformed
        // TODO: test the findItem() method 
        final String items[] = {"bat", "cow", "CAT", "Goat", "fox"}; 
       String msg = "";  
       
        // read the text box for the search value 
        // get some mileage out of our user defined method 
        String item = txtInput1.getText();  
        
        // call or invole our user define method to search the array 
        int result = MyUtils.findItem(items, item); 
        
        // evaluate our result and display the index if found or a not found 
        // message if not found 
        // hint for excersize 2 of this lab 
        if (result > -1) {
            // found it - display the index or subscript 
            msg = "Found item at subscript " + Integer.toString(result); 
        } 
        else {
            msg = "NOT FOUND"; 
        }  
        // DISPLAY THE RESULT 
        lblResult.setText(msg); 
        
    }//GEN-LAST:event_btnSearchStringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MethodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MethodForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFormat;
    private javax.swing.JButton btnIsInt;
    private javax.swing.JButton btnParseInt;
    private javax.swing.JButton btnSearchInt;
    private javax.swing.JButton btnSearchString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtInput1;
    private javax.swing.JTextField txtInput2;
    // End of variables declaration//GEN-END:variables
}
